apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}

  - name: Elasticsearch-Fluentd
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}
    url: ${PROMETHEUS_URL}
    isDefault: true
    version: 1
    editable: true

  - name: Elasticsearch-Fluentd
    type: elasticsearch
    access: proxy
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}
    url: ${ELASTICSEARCH_URL}
    database: '[fluentd-]YYYYMM'
    basicAuth: true
    basicAuthUser: ${ELASTICSEARCH_USER}
    secureJsonData:
      basicAuthPassword: ${ELASTICSEARCH_PASS}
    timeInterval: 1m
    esVersion: 60
    timeField: '@timestamp'
    interval: Monthly
    version: 1
    editable: true
