version: '3.7'

services:
  grafana:
    image: ${IMAGE_NAME:-grafana/grafana}:${IMAGE_TAG:-latest}
    environment:
      GF_PATHS_DATA:
      GF_PATHS_PROVISIONING:
      GF_INSTALL_PLUGINS:
      GF_SERVER_ROOT_URL: ${TRAEFIK_PROTOCOL}://${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}
      GF_SERVER_HTTP_PORT:
      GF_SERVER_ENABLE_GZIP:
      GF_SECURITY_ADMIN_USER:
      GF_SECURITY_ADMIN_PASSWORD:
      GF_USERS_ALLOW_SIGN_UP:
      GF_USERS_AUTO_ASSIGN_ORG:
      GF_USERS_AUTO_ASSIGN_ORG_ID:
      GF_USERS_AUTO_ASSIGN_ORG_ROLE:
      GF_SMTP_ENABLED:
      GF_SMTP_FROM_ADDRESS:
      GF_SMTP_FROM_NAME:
      GF_SMTP_HOST:
      GF_SMTP_SKIP_VERIFY:
      GF_SMTP_USER:
      GF_SMTP_PASSWORD:
      GF_LOG_MODE:
      GF_LOG_LEVEL:
      DASHBOARDS_PATH:
      PROMETHEUS_URL:
    networks:
      metric-net:
      traefik-net:
      mail-net:
    volumes:
      - data-vol:${GF_PATHS_DATA}
    configs:
      - source: datasources-config
        target: ${GF_PATHS_PROVISIONING}/datasources/datasources.yml
      - source: dashboards-providers-config
        target: ${GF_PATHS_PROVISIONING}/dashboards/dashboards_providers.yml
      - source: nodes-dashboard-config
        target: ${DASHBOARDS_PATH}/swarmprom-nodes.json
      - source: services-dashboard-config
        target: ${DASHBOARDS_PATH}/swarmprom-services.json
      - source: prometheus-dashboard-config
        target: ${DASHBOARDS_PATH}/swarmprom-prometheus.json
      - source: docker-dashboard-config
        target: ${DASHBOARDS_PATH}/docker.json
      - source: traefik2-dashboard-config
        target: ${DASHBOARDS_PATH}/traefik2.json
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.http.routers.grafana.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.grafana.tls.certresolver: ${TRAEFIK_CERTRESOLVER:-default}
        traefik.http.routers.grafana.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.grafana.loadbalancer.server.port: ${GF_SERVER_HTTP_PORT}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

  mail-net:
    name: ${MAIL_NET_NAME:-mail-net}
    external: true

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-grafana-vol}
    driver: local
    driver_opts:
      type: ${DATA_VOL_TYPE:-nfs}
      o: ${DATA_VOL_OPTIONS}
      device: ${DATA_VOL_DEVICE:-:/grafana-vol/}

configs:
  datasources-config:
    name: ${DATASOURCES_CONFIG_NAME:-grafana-datasources}
    file: ./config/datasources.yml

  dashboards-providers-config:
    name: ${DASHBOARDS_PROVIDERS_CONFIG_NAME:-grafana-dashboards-providers}
    file: ./config/dashboards_providers.yml

  nodes-dashboard-config:
    name: ${NODES_DASHBOARD_CONFIG_NAME:-grafana-nodes-dashboard}
    file: ./config/dashboards/swarmprom-nodes.json

  services-dashboard-config:
    name: ${SERVICES_DASHBOARD_CONFIG_NAME:-grafana-services-dashboard}
    file: ./config/dashboards/swarmprom-services.json

  prometheus-dashboard-config:
    name: ${PROMETHEUS_DASHBOARD_CONFIG_NAME:-grafana-prometheus-dashboard}
    file: ./config/dashboards/swarmprom-prometheus.json

  docker-dashboard-config:
    name: ${DOCKER_DASHBOARD_CONFIG_NAME:-grafana-docker-dashboard}
    file: ./config/dashboards/docker.json

  traefik2-dashboard-config:
    name: ${TRAEFIK2_DASHBOARD_CONFIG_NAME:-grafana-traefik2-dashboard}
    file: ./config/dashboards/traefik2.json
